### PR TITLE
Dark Mode + Delete Button

### PR DESCRIPTION
**Pull request by Harshal2502**
Ready to push the commits to the main branch, the earlier commits were not in sync with the main branch. Sorry for that

### CODE REVIEW

**Comment by Harshal2502** [comment]
Added Check-box

**Comment by VG-1** [comment]
hey @Harshal2502 can you send a video or gif for the same?

**Comment by Harshal2502** [comment]
@VG-1 Sure, Here's a demo GIF for it!
ezgif com-gif-maker

**Comment by VG-1** [comment]
Hey @Harshal2502 thanks 
Oreo's are good only :))

Merging your PR.
Stay connected :)

**Comment by Harshal2502** [comment]
Thanks for accepting 😁✌️

**Comment by VG-1** [comment]
Hey @Harshal2502 oreo is good only :)
Merging your PR.
Thanks for contributing, Stay Connected :))

**Comment by varunKT001** [comment]
@VG-1 The delete functionality was assigned to me 😢

**Pull request merged**
